### ISSUE TITLE
Foreign key error

### ISSUE THREAD

**Issue by VTula2000** [GSS-Cogs/ONS-International-Trade-in-Services#2]
unmatched_foreign_key_reference. Row: 4,1. ["..."]
unmatched_foreign_key_reference. Row: 5,1. ["."]

**Comment by VTula2000** [comment]
Foreign_keys ["..."] and ["."] definition not available in source data

**Comment by grace-spitzer-wong** [comment]
@VTula2000 Hey Vamshi, going to have a look at this

**Comment by ajtucker** [comment]
It looks as though, in https://github.com/GSS-Cogs/ONS-International-Trade-in-Services/blob/master/main.py#L132, you're missing these `.` and `...` markers?

@Grace-W , can you have a look at the spreadsheet to figure out what these markers mean? We can then work out whether they need adding to ref_trade/codelists/markers.csv and tell @VTula2000 what codes to use.

**Comment by ajtucker** [comment]
Looking through the spreadsheet at https://www.ons.gov.uk/file?uri=/businessindustryandtrade/internationaltrade/datasets/internationaltradeinservicesreferencetables/alltables2017/internationaltradeinservices2017.xls these markers `.` and `...` seem to be mistakes.

@Grace-W, can you double-check through the spreadsheet and confirm? If so, then both `.` and `...` will probably mean the same as `..`, i.e. disclosive.

@VTula2000 would you be able to turn `.` and `...` into `disclosive` once @Grace-W has confirmed?

**Comment by grace-spitzer-wong** [comment]
@VTula2000 @ajtucker Both `.` and `...` are mistakes and are the same as disclosive so can be changed.

@VTula2000 - once it's changed over, please can you close the ticket?

Thank you

**Comment by ajtucker** [comment]
#3 is now raised by Jenkins, tracking the same issue. Fixing this should automatically close #3 unless there are other problems with the pipeline.
